DROP TYPE IF EXISTS JUBLAWOMA_DONATION_PRODUCT_UNIT CASCADE;
CREATE TYPE JUBLAWOMA_DONATION_PRODUCT_UNIT AS ENUM ('KILOGRAM', 'LITER', 'PIECE', 'TUBE', 'JAR', 'BOX', 'FRANCS');
CREATE CAST (varchar AS JUBLAWOMA_DONATION_PRODUCT_UNIT) WITH INOUT AS IMPLICIT;
