DROP TYPE IF EXISTS SHARED_ACCOUNT_PERMISSION_PERMISSION CASCADE;
CREATE TYPE SHARED_ACCOUNT_PERMISSION_PERMISSION AS ENUM ('JUBLAWOMA_ADMIN');
CREATE CAST (varchar AS SHARED_ACCOUNT_PERMISSION_PERMISSION) WITH INOUT AS IMPLICIT;
