DROP TYPE IF EXISTS SHARED_COMMUNICATION_TYPE CASCADE;
CREATE TYPE SHARED_COMMUNICATION_TYPE AS ENUM ('EMAIL');
CREATE CAST (varchar AS SHARED_COMMUNICATION_TYPE) WITH INOUT AS IMPLICIT;

DROP TYPE IF EXISTS SHARED_COMMUNICATION_STATUS CASCADE;
CREATE TYPE SHARED_COMMUNICATION_STATUS AS ENUM ('OPEN', 'IN_PROGRESS', 'SUCCESS', 'ERROR');
CREATE CAST (varchar AS SHARED_COMMUNICATION_STATUS) WITH INOUT AS IMPLICIT;
