services:
  db:
    image: legacy-db
    restart: always
    ports:
      - 5432:5432
    networks:
      - websites-network
    volumes:
      - "websites-db-volume:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${SECRET_DB_PASSWORD}
  api:
    image: legacy-api
    restart: always
    ports:
      - 8080:8080
    networks:
      - websites-network
    volumes:
      - "websites-api-volume:/data"
    environment:
      - SECRET_DATABASE=${SECRET_DB_PASSWORD}
  ui:
    image: legacy-ui
    restart: always
    ports:
      - 8000:8000
    networks:
      - websites-network

networks:
  websites-network:
    driver: bridge

volumes:
  websites-db-volume:
  websites-api-volume:
