services:

  websites-db:
    image: websites-db:${VERSION_API}
    restart: always
    ports:
      - 5432:5432
    networks:
      - websites-network
    volumes:
      - "websites-db-volume:/data"
    environment:
      - SECRET_DB_PASSWORD=${SECRET_DB_PASSWORD}

  websites-api:
    image: websites-api:${VERSION_API}
    restart: always
    ports:
      - 8080:8080
    networks:
      - websites-network
    volumes:
      - "websites-api-volume:/data"
    environment:
      - SECRET_DB_PASSWORD=${SECRET_DB_PASSWORD}

  websites-ui:
    image: websites-ui:${VERSION_API}
    restart: always
    ports:
      - 8000:8000
    networks:
      - websites-network

networks:
  websites-network:

volumes:
  websites-db-volume:
  websites-api-volume:
