services:

  websites-api:
    image: websites-api:${VERSION_API}
    restart: always
    ports:
      - 8080:8080
    networks:
      - websites-network
    volumes:
      - "websites-api-volume:/data"
    environment:
      - SECRET_DATABASE=${SECRET_DATABASE}

networks:
  websites-network:

volumes:
  websites-database-volume:
  websites-backend-volume:
