export enum Enviroment {
  JUBLAWOMA = "JUBLAWOMA",
  JUBLAWOMA_ADMIN = "JUBLAWOMA_ADMIN",
  UNCLET = "UNCLET",
  UNCLET_ADMIN = "UNCLET_ADMIN",
  OLIUMBI = "OLIUMBI",
  OLIUMBI_ADMIN = "OLIUMBI_ADMIN"
}
