services:
  database:
    image: test-database # ghcr.io/oliumbi/websites-database
    restart: always
    ports:
      - 5432:5432
    networks:
      - websites-network
    volumes:
      - "websites-database-volume:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${SECRET_DATABASE_PASSWORD}
  migration:
    image: test-migration # ghcr.io/oliumbi/websites-migration
    restart: on-failure
    networks:
      - websites-network
    environment:
      - FLYWAY_PASSWORD=${SECRET_DATABASE_PASSWORD}
    depends_on:
      - database
  api:
    image: test-api # ghcr.io/oliumbi/websites-api
    restart: always
    ports:
      - 8080:8080
    networks:
      - websites-network
    volumes:
      - "websites-api-volume:/data"
    environment:
      - SECRET_DATABASE_PASSWORD=${SECRET_DATABASE_PASSWORD}
    depends_on:
      - database
  ui:
    image: test-ui # ghcr.io/oliumbi/websites-ui
    restart: always
    ports:
      - 8000:8000
    networks:
      - websites-network

networks:
  websites-network:
    driver: bridge

volumes:
  websites-database-volume:
  websites-api-volume:
