name: publish

on:
  push:
    tags:
      - '*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: |
            ghcr.io/oliumbi/websites-database:latest
            ghcr.io/oliumbi/websites-database:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push migration
        uses: docker/build-push-action@v6
        with:
          context: ./migration
          tags: |
            ghcr.io/oliumbi/websites-migration:latest
            ghcr.io/oliumbi/websites-migration:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          tags: |
            ghcr.io/oliumbi/websites-api:latest
            ghcr.io/oliumbi/websites-api:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push ui
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          tags: |
            ghcr.io/oliumbi/websites-ui:latest
            ghcr.io/oliumbi/websites-ui:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
